micronaut:
  application:
    name: micronaut-inaction
  server:
    port: 8080
  executors:
    io:
      type: fixed
      nThreads: 75
  netty:
    event-loops:
      other:
        num-threads: 10
api:
  regres:
    url: https://reqres.in/api



